config/routes.rb
Rails.application.routes.draw do

  root 'referrals#new'

  resources :students
  resources :referrals
  resources :rosters
  resources :staff_members

  post '/rosters/:id/title', to: 'rosters#title', as: 'roster_title'
  post '/referrals/filter', to: 'referrals#filter_students', as: 'filter_students'

  devise_for :staff_members,
    :controllers => {:registrations => "staff_members/registrations"},
    path_names: {sign_up: ''}

end

app/models/referral.rb
class Referral < ActiveRecord::Base
  belongs_to :student
  belongs_to :staff_member
  has_many :infractions, through: :referral_infractions

  validates :student_id, presence: true
  validates :staff_member_id, presence: true

  def self.build_from_form_input(params, referral_params)
    @@params = params
    @@referral_params = referral_params
    type = @@params[:referral][:referral_type]

    build_discipline if type == "discipline"
    build_uniform if type == "uniform"
    build_tardy if type == "tardy"
    build_positive if type == "acclaim"
  end

  private

  def self.build_positive
    referral = create_referral
    referral.update_attribute(:student_id, @@params[:referral][:student_id][0].to_i)
    referral.save
  end

  def self.build_discipline
    referral = create_referral
    @@params[:referral][:infractions].each do | input |
      ReferralInfraction.create(referral_id: referral.id, infraction_id: Infraction.find_by(name: input).id)
    end
    referral.update_attribute(:student_id, @@params[:referral][:student_id][0].to_i)
    referral.save
  end

  def self.build_uniform
    @@params[:referral][:students].each do |student_id|
      referral = create_referral
      referral.student_id = student_id.to_i
      referral.update_attribute(:anecdotal, "Student was out of uniform.")
      referral.save
    end
  end

  def self.build_tardy
    @@params[:referral][:students].each do |student_id|
      referral = create_referral
      referral.student_id = student_id.to_i
      if !!(@@params[:minutes])
        referral.update_attribute(:anecdotal, "Student was #{@@params[:minutes]} minutes late to class.")
      else
        referral.update_attribute(:anecdotal, "Student was late to class.")
      end
      referral.save
    end
  end

  def create_referral
    referral = Referral.create(@@referral_params)
    referral.date = @@params["referral"][:date][0].to_date || DateTime.now.to_date
  end

end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  def index
    @referrals = Referral.all
  end

  def show
  end

  def new
    @referral = Referral.new
    @students = current_staff_member.school.students.all
  end

  def create
    Referral.build_from_form_input(params, referral_params)
    redirect_to new_referral_path
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

  def search_students

  end

  def filter_students
    if Roster.exists?(params[:roster_id])
      @students = Roster.find(params[:roster_id]).students
    else
      @students = current_staff_member.school.students
    end

    respond_to do |format|
      format.html { render partial: 'student_checklist'}
      format.js { render partial: 'student_checklist'}
      format.json { render partial: 'student_checklist'}
    end
  end

  private
  def referral_params
    params.require(:referral).permit(:student_id, :date, :anecdotal, :additional_information, :deans_referral?, :positive?, :location, :period, :referral_type, :students, :staff_member_id, :infractions, :minutes)
  end

end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_date.html.erb
<div class="form-group">
  <%= label_tag(:date, nil, class:"control-label") %>: Optional. You only need to complete this if you are not writing the referral on the date of the incident.
  <div class="controls">
    <div class="input-group date col-sm-4">
      <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
      <%= date_field("referral[date]", nil, class:"form-control date-picker") %>
    </div>
  </div>
</div>

app/views/referrals/_negative.html.erb
  <h1>Create a New Report - Referral</h1>
  
<%= form_tag(referrals_path) do |f| %>
  <div class="form-group">
    <%= check_box_tag("referral[deans_referral?][]", "true") %>
    <%= label_tag("This is a dean's referral stemming from an incident that resulted in suspension.") %><br />
  </div>


  <%= render partial: 'date' %>
  <%= render partial: 'student_name_input' %>

  <div class="form-group">
    <%= label_tag(:period) %>: <br />
    <%= text_field_tag("referral[period]", nil, class:"form-control") %><br />
  </div>

  <%= hidden_field_tag("referral[positive?]", "false", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[referral_type]", "discipline", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[staff_member_id]", current_staff_member.id, class:"form-control text-area-input") %><br />

  <div class="form-group">
    <%= label_tag(:location) %>: <br />
    <%= text_field_tag("referral[location]", nil, class:"form-control") %><br />
  </div>

  <div class="form-group">
    <% Infraction.all.each do |infraction| %>
    <%= check_box_tag("referral[infractions][]", infraction.name) %>
    <%= label_tag(infraction.name) %><br />
    <% end %>
    <!-- <%= check_box_tag("referral[infractions][]", "bullying_or_threatening_behavior") %>
    <%= label_tag(:bullying_or_threatening_behavior) %><br />
    <%= check_box_tag("referral[infractions][]", "Inappropriate sexual behavior") %>
    <%= label_tag(:inappropriate_sexual_behavior) %><br />
    <%= check_box_tag("referral[infractions][]", "Vandalism") %>
    <%= label_tag(:vandalism) %><br />
    <%= check_box_tag("referral[infractions][]", "Insubordination") %>
    <%= label_tag(:insubordination) %><br />
    <%= check_box_tag("referral[infractions][]", "Profanity") %>
    <%= label_tag(:profanity) %><br />
    <%= check_box_tag("referral[infractions][]", "Disrupting the educational process") %>
    <%= label_tag(:disrupting_the_educational_process) %><br /> -->
  </div>

  <div class="form-group">
    <%= label_tag(:anecdotal) %>: <br />
    <%= text_area_tag("referral[anecdotal]", nil, class:"form-control text-area-input") %><br />
  </div>
  <div class="form-group">
    <%= label_tag(:additional_information) %>:<br />
    <%= text_area_tag("referral[additional_information]", nil, class:"form-control text-area-input") %><br />
  </div>

  <%= submit_tag("Submit") %>
<% end %>

app/views/referrals/_positive.html.erb
<h1>Create a New Report - Acclaim</h1>
<%= form_tag(referrals_path) do |f| %>

  <%= render partial: 'date' %>
  <%= render partial: 'student_name_input' %>

  <div class="form-group">
    <%= label_tag(:period) %>: <br />
    <%= text_field_tag("referral[period]", nil, class:"form-control") %><br />
  </div>

  <%= hidden_field_tag("referral[positive?]", "true", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[referral_type]", "acclaim", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[staff_member_id]", current_staff_member.id, class:"form-control text-area-input") %><br />

  <div class="form-group">
    <%= label_tag(:anecdotal) %>: <br />
    <%= text_area_tag("referral[anecdotal]", nil, class:"form-control text-area-input") %><br />
  </div>

  <%= submit_tag("Submit") %>
<% end %>

app/views/referrals/_student_name_input.html.erb
<!-- <div class="form-group">
  <%# label_tag(:student_name, nil, class:"control-label") %>:<br />
  <div class="controls">
    <div class="input-group col-sm-4">
      <%# text_field_tag("referral[student_id]", nil, class:"form-control student_name_input_field") %>
      <%# render partial: 'student_names_suggestions' %>
    </div>
  </div>
</div> -->


<div class="form-group">
  <%= label_tag(:student_name, nil, class:"control-label") %>:<br />
  <div class="controls">
    <div id="student-name-input-field" class="input-group col-sm-4">
      <%= select_tag("referral[student_id]", options_from_collection_for_select(@students, 'id', "full_name"), class:"referral_student_id form-control") %>
    </div>
  </div>
</div>

app/views/referrals/_student_names_suggestions.html.erb
<div id="student_name_suggestions" style="display:none">
  <% @students.each do |student| %>
    <div class="individual-student-name">
      <%= student.full_name %>
    </div>
  <% end %>
</div>

app/views/referrals/_tardy.html.erb
<h1>Create a New Report - Student Lateness</h1>

<select name="rosters" class="roster-drop-down">
  <option value="-1"></option>
  <% current_staff_member.rosters.each do |roster| %>
    <option value= <%= roster.id %>><%= roster.title %> </option>
  <% end %>
</select>

<%= form_tag(referrals_path) do |f| %>

  <%= render partial: 'date' %>

  <div class="form-group">
    <%= label_tag(:period) %>: <br />
    <%= text_field_tag("referral[period]", nil, class:"form-control") %><br />
  </div>

  <div class="form-group">
    <%= label_tag("Minutes (optional)") %>: <br />
    <%= text_field_tag("referral[minutes]") %><br />

  </div>

  <%= hidden_field_tag("referral[positive?]", "false", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[referral_type]", "tardy", class:"form-control text-area-input") %><br />
  <%= hidden_field_tag("referral[staff_member_id]", current_staff_member.id, class:"form-control text-area-input") %><br />

  <div class="form-group student-checklist">
    <%= render partial: 'student_checklist' %>
  </div>

  <%= submit_tag("Submit") %>
<% end %>

app/views/referrals/_uniform.html.erb
<h1>Create a New Report - Uniform Violation</h1>

<select name="rosters" class="roster-drop-down">
  <option value="-1"></option>
  <% current_staff_member.rosters.each do |roster| %>
    <option value= <%= roster.id %>><%= roster.title %> </option>
  <% end %>
</select>

<%= form_tag(referrals_path) do |f| %>

  <%= render partial: 'date' %>

  <div class="form-group">
    <%= label_tag(:period) %>: <br />
    <%= text_field_tag("referral[period]", nil, class:"form-control") %><br />
  </div>

  <div class="hidden">
    <%= hidden_field_tag("referral[positive?]", "false") %><br />
    <%= hidden_field_tag("referral[referral_type]", "uniform") %><br />
    <%= hidden_field_tag("referral[anecdotal]", "Student was out of uniform.") %><br />
    <%= hidden_field_tag("referral[staff_member_id]", current_staff_member.id, class:"form-control text-area-input") %><br />
  </div>

  <div class="form-group student-checklist">
    <%= render partial: 'student_checklist' %>
  </div>

  <%= submit_tag("Submit") %>
<% end %>

app/views/referrals/create.html.erb
<h1>Referrals#create</h1>
<p>Find me in app/views/referrals/create.html.erb</p>

app/views/referrals/delete.html.erb
<h1>Referrals#delete</h1>
<p>Find me in app/views/referrals/delete.html.erb</p>

app/views/referrals/destroy.html.erb
<h1>Referrals#destroy</h1>
<p>Find me in app/views/referrals/destroy.html.erb</p>

app/views/referrals/new.html.erb
<div class="col-lg-6 col-md-6 visible-md visible-lg visible-sm visible-xs clementine-content" id="referral-page">
  <div id="referral-navigation-tabs">
    <button class="btn btn-lg btn-success referral-tab" id="commendation">Acclaim</button>
    <button class="btn btn-lg btn-danger referral-tab" id="referral">Referral</button>
    <button class="btn btn-lg btn-warning referral-tab" id="uniform">Uniform</button>
    <button class="btn btn-lg btn-primary referral-tab" id="tardy">Tardy</button>

  </div>

  <div id="negative-referral-form">
    <%= render partial: 'negative' %>
  </div>
  <div id="positive-referral-form" style="display:none">
    <%= render partial: 'positive' %>
  </div>
  <div id="tardy-referral-form" style="display:none">
    <%= render partial: 'tardy' %>
  </div>
  <div id="uniform-referral-form" style="display:none">
    <%= render partial: 'uniform' %>
  </div>
</div>

<% if !!current_staff_member %>
  <%= render partial: 'activity_feed' %>
<% end %>

app/views/referrals/show.html.erb
<h1>Referrals#show</h1>
<p>Find me in app/views/referrals/show.html.erb</p>

app/views/referrals/update.html.erb
<h1>Referrals#update</h1>
<p>Find me in app/views/referrals/update.html.erb</p>